services:
  php:
    build: .
    ports:
      - "8080:80" # Exponera port 80 på containern till port 8080 på värddatorn
    volumes:
      - .:/var/www/html # Koppla koden från värddatorn till containern
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Exponera MySQL-porten
